abstract class ApiKeys{
  static const String publishableKey = "pk_test_51QtDckPqdIE2o1bfi9z3ZgYklTR2gTnA58USu0dsFwCsDQTUSh87DvPtPqcPLklFmbnrdLW7MEYqqKCacTRFO61P00IZBpARoD";
  static const String secretKey = "sk_test_51QtDckPqdIE2o1bfCRdOBqPJDp2jFf7YHubiIInCFsOrcKsQd9SYxqjmV7EcvvDkJXX7nKdvdOgvkXzmqY7vpFF800EIZLqQ8M";
}